import { rgba } from 'polished';

export const BLACK = 'black';
export const BLACK_90 = rgba(BLACK, 0.9);
export const BLACK_50 = rgba(BLACK, 0.5);
const BLACK_LIGHTER = '#010101';
export const BLACK_LIGHTER_95 = rgba(BLACK_LIGHTER, 0.95);
export const DARK_SLATE_GREY = 'darkslategrey';
export const GRAY = '#808080';
const GRAY_MEDIUM = 'rgb(100,100,100)';
export const GRAY_MEDIUM_10 = rgba(GRAY_MEDIUM, 0.1);
export const GRAY_LIGHT = '#ccc';
export const RED = 'red';
export const RED_70 = rgba(RED, 0.7);
export const RED_50 = rgba(RED, 0.5);
export const ROSE_WOOD = '#640000';
export const ROSE_WOOD_50 = rgba(ROSE_WOOD, 0.5);
export const SHARK_DARK = '#262629';
export const SHARK_DARK_70 = rgba(SHARK_DARK, 0.7);
export const WHITE = 'white';
export const WHITE_20 = rgba(WHITE, 0.2);
export const WHITE_50 = rgba(WHITE, 0.5);
export const WHITE_80 = rgba(WHITE, 0.8);
export const WHITE_90 = rgba(WHITE, 0.9);
export const WHITE_95 = rgba(WHITE, 0.95);
export const WHITE_SMOKE = 'whitesmoke';
export const WHITE_SMOKE_10 = rgba(WHITE_SMOKE, 0.1);
